{
 "title": "JumpServer",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Core",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job_name=\"core\"} |= `${search}`"
    }
   ]
  },
  {
   "title": "Web",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"web\"} |= `${search}`"
    }
   ]
  },
  {
   "title": "Koko",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"koko\"} |= `${search}`",
     "maxLines": 50
    }
   ]
  },
  {
   "title": "Lion",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"lion\"} |= `${search}`"
    }
   ]
  },
  {
   "title": "Razor",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{component=\"razor\"} |= `${search}`"
    },
    {
     "expr": "{container=\"jms_razor\"} |= `${search}`"
    }
   ]
  },
  {
   "title": "XRDP",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"jms_xrdp\"} |= `${search}`"
    },
    {
     "expr": "{component=\"xrdp\"} |= `${search}`"
    }
   ]
  },
  {
   "title": "Chen",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{component=\"chen\"} |= `${search}`"
    }
   ]
  },
  {
   "title": "Magnus",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{component=\"magnus\"} |= `${search}`"
    }
   ]
  }
 ]
}