services:
  chen:
    image: ${REGISTRY:-docker.io}/jumpserver/chen-ce:${VERSION}
    container_name: jms_chen
    hostname: jms_chen
    ulimits:
      core: 0
    restart: always
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${VOLUME_DIR}/chen/data:/opt/chen/data
      - ${CONFIG_DIR}/certs:/opt/chen/data/certs
    healthcheck:
      test: "check http://localhost:8082/chen/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - net