services:
  core:
    image: ${REGISTRY:-docker.io}/jumpserver/core-ce:${VERSION}
    container_name: jms_core
    hostname: jms_core
    ulimits:
      core: 0
    restart: always
    command: start web
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${CONFIG_DIR}/certs:/opt/jumpserver/data/certs
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    healthcheck:
      test: "check http://localhost:8080/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - net