version: '2.4'

services:
  nginx:
    ports:
      - ${HTTP_PORT}:80
      - ${SSH_PORT}:2222
      - ${RDP_PORT}:3389
    volumes:
      - ./config_static/http_server.conf:/etc/nginx/conf.d/default.conf
      - ${CONFIG_DIR}/nginx/lb_ssh_server.conf:/etc/nginx/stream.d/ssh_server.conf
      - ${CONFIG_DIR}/nginx/cert:/etc/nginx/cert
      - ${VOLUME_DIR}/core/data:/data
      - ${VOLUME_DIR}/nginx/log:/var/log/nginx
