version: '2.4'

services:
  nginx:
    volumes:
      - ./config_static/http_server.conf:/etc/nginx/conf.d/default.conf
      - ${CONFIG_DIR}/nginx/cert:/etc/nginx/cert
      - ${VOLUME_DIR}/core/data:/data
      - ${VOLUME_DIR}/nginx/log:/var/log/nginx
