version: '2.4'

services:
  kael:
    image: ${REGISTRY:-docker.io}/jumpserver/kael:${VERSION}
    container_name: jms_kael
    hostname: jms_kael
    ulimits:
      core: 0
    restart: always
    tty: true
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${CONFIG_DIR}/certs:/opt/kael/data/certs
      - ${VOLUME_DIR}/kael/data:/opt/kael/data
    healthcheck:
      test: "curl -fsL http://localhost:8083/kael/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - net