services:
  lion:
    image: ${REGISTRY:-docker.io}/jumpserver/lion:${VERSION}
    container_name: jms_lion
    hostname: jms_lion
    ulimits:
      core: 0
    restart: always
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${CONFIG_DIR}/certs:/opt/lion/data/certs
      - ${VOLUME_DIR}/lion/data:/opt/lion/data
    healthcheck:
      test: "curl -fsL http://localhost:8081/lion/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net