services:
  receptor:
    image: ${REGISTRY:-docker.io}/jumpserver/core-ce:${VERSION}
    container_name: jms_receptor
    hostname: jms_receptor
    ulimits:
      core: 0
    restart: always
    command: start receptor
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ${VOLUME_DIR}/core/data/share:/opt/jumpserver/data/share
    healthcheck:
      test: "nc -z 127.0.0.1 7521 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - net
