services:
  magnus:
    image: ${REGISTRY:-docker.io}/jumpserver/magnus:${VERSION}
    container_name: jms_magnus
    hostname: jms_magnus
    ulimits:
      core: 0
    restart: always
    tty: true
    env_file:
      - ${CONFIG_FILE}
    ports:
      - ${MAGNUS_MYSQL_PORT:-33061}:33061
      - ${MAGNUS_MARIADB_PORT:-33062}:33062
      - ${MAGNUS_REDIS_PORT:-63790}:63790
    volumes:
      - ${CONFIG_DIR}/certs:/opt/magnus/data/certs
      - ${VOLUME_DIR}/magnus/data:/opt/magnus/data
    healthcheck:
      test: "curl localhost:8088/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net
