services:
  kael:
    image: ${NAMESPACE:-jumpserver}/kael:${VERSION}
    container_name: jms_kael
    hostname: jms_kael
    ulimits:
      core: 0
    restart: always
    env_file:
      - ${CONFIG_SAFE_FILE}
    environment:
      PLATFORM_GATEWAY_ENABLED: "true"
      PLATFORM_DELEGATION_KEY: ${CHAT_AI_DELEGATION_SECRET}
    volumes:
      - ${VOLUME_DIR}/kael/data:/opt/kael/data
    healthcheck:
      test: "check http://localhost:8083/kael/health/ready"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - net
