services:
  koko:
    image: ${REGISTRY:-docker.io}/jumpserver/koko:${VERSION}
    container_name: jms_koko
    hostname: jms_koko
    ulimits:
      core: 0
    restart: always
    privileged: true
    env_file:
      - ${CONFIG_FILE}
    environment:
      - SSHD_PORT=${SSH_PORT:-2222}
    ports:
      - ${SSH_PORT:-2222}:${SSH_PORT:-2222}
    volumes:
      - ${CONFIG_DIR}/certs:/opt/koko/data/certs
      - ${VOLUME_DIR}/koko/data:/opt/koko/data
    healthcheck:
      test: "check http://localhost:5000/koko/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net