services:
  magnus:
    image: ${REGISTRY:-registry.fit2cloud.com}/jumpserver/magnus:${VERSION}
    container_name: jms_magnus
    hostname: jms_magnus
    ulimits:
      core: 0
    restart: always
    env_file:
      - ${CONFIG_FILE}
    ports:
      - ${MAGNUS_MYSQL_PORT:-33061}:${MAGNUS_MYSQL_PORT:-33061}
      - ${MAGNUS_MARIADB_PORT:-33062}:${MAGNUS_MARIADB_PORT:-33062}
      - ${MAGNUS_REDIS_PORT:-63790}:${MAGNUS_REDIS_PORT:-63790}
      - ${MAGNUS_POSTGRESQL_PORT:-54320}:${MAGNUS_POSTGRESQL_PORT:-54320}
      - ${MAGNUS_SQLSERVER_PORT:-14330}:${MAGNUS_SQLSERVER_PORT:-14330}
      - ${MAGNUS_ORACLE_PORT:-15210}:${MAGNUS_ORACLE_PORT:-15210}
      - ${MAGNUS_MONGODB_PORT:-27018}:${MAGNUS_MONGODB_PORT:-27018}
    volumes:
      - ${CONFIG_DIR}/certs:/opt/magnus/data/certs
      - ${VOLUME_DIR}/magnus/data:/opt/magnus/data
    healthcheck:
      test: "curl localhost:8088/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net
