services:
  postgresql:
    image: postgres:16.3-bullseye
    container_name: jms_postgresql
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ${VOLUME_DIR}/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -q -U $$POSTGRES_USER"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - net